sudo: false
language: node_js

node_js:
  - "8.14"

script :
  - npm install
  - npm run build
  - mv dist/* .
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard

