sudo: false
language: node_js

node_js:
  - "8.14"

script :
  - cd website/
  - npm install
  - npm run build
  - mv build/* .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: website/

